name = "TechnoCraft: Bainos"
author = "Andr√© Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daaf27af80a64b0f2a060a9f6b5a64af3ec476ffc6428b198a9ccefa2465b670"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
